version: "3.7"

services:
  frontend:
    image: tomfordweb/devonwick-clp-frontend:lastest
    networks:
      - app-network

  backend:
    image: tomfordweb/devonwick-clp-backend:lastest
    container_name: devonwick-backend
    restart: unless-stopped
    networks:
      - app-network
    entrypoint:
      [
        "uvicorn",
        "app.main:app",
        "--proxy-headers",
        "--reload",
        "--host",
        "0.0.0.0",
        "--root-path",
        "/api/v1",
      ]

  proxy:
    image: tomfordweb/devonwick-clp-proxy:lastest
    networks:
      - app-network
    ports:
      - 8080:80

networks:
  app-network:
    driver: bridge
