version: "3.7"

services:
  frontend:
    image: tomfordweb/devonwick-clp-frontend:lastest
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
      args:
        REACT_APP_CI_BUILD: "production"
    networks:
      - app-network

  backend:
    image: tomfordweb/devonwick-clp-backend:lastest
    container_name: devonwick-backend
    restart: unless-stopped
    networks:
      - app-network
    build:
      context: ./backend
    entrypoint:
      [
        "uvicorn",
        "app.main:app",
        "--proxy-headers",
        "--reload",
        "--host",
        "0.0.0.0",
        "--root-path",
        "/api/v1",
      ]

  proxy:
    image: tomfordweb/devonwick-clp-proxy:lastest
    build:
      context: ./proxy
    networks:
      - app-network
    ports:
      - 8080:80

networks:
  app-network:
    driver: bridge

volumes:
  appdb:
