version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend-local.Dockerfile
    entrypoint: ["npm", "start"]
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_CI_BUILD=local
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/package.json:/app/package.json
    ports:
      - 35729:35729

  backend:
    build:
      context: ./backend
    environment:
      # DO NOT USE THIS IN ANYWHERE OTHER THAN A TESTING OR DEVELOPMENT ENVIRONMENT
      SECRET_KEY: "7880a54f2e77f3d7cac9c6d5387e0821b2a4b8a1c6429adaa1d534ad6f6a7120"
    volumes:
      - ./backend:/clp
    # restart: unless-stopped

  proxy:
    build:
      context: ./proxy
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
