#!/bin/bash


RECIPIENTS="me+infrastructure@tomfordweb.net"
DATABASE=$1

zip /tmp/database_backup.zip $DATABASE

echo "
Backup Date:
$(date)

Size:
$(du -h $DATABASE)
" > /tmp/clp_backup_message

for recipient in $recipients; do
  mpack -s "Devonwick CLP Database Backup" -d /tmp/clp_backup_message /tmp/database_backup.zip $recipient
done;


