"""add custom name

Revision ID: 3469b054e6e1
Revises: 6d9d42f29ce1
Create Date: 2022-01-08 17:09:47.577361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3469b054e6e1'
down_revision = '6d9d42f29ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('custom_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_custom_name'), 'products', ['custom_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_custom_name'), table_name='products')
    op.drop_column('products', 'custom_name')
    # ### end Alembic commands ###
