name: Build and push to dockerhub

on:
  push:
    branches:
      - "main"
      - "ci"

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/frontend.Dockerfile
          push: true
          tags: tomfordweb/devonwick-clp:latest

  deploy-development:
    runs-on: ubuntu-latest
    needs: [build-docker]
    steps:
      - name: Install SSH Key for DEV_SERVER
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEV_SERVER_SSH_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: Add Dev server to known hosts
        run: ssh-keyscan -H ${{ secrets.DEV_SERVER }} >> ~/.ssh/known_hosts
      - name: Login to docker registry
        run: ssh ${{ secrets.DEV_SERVER_USER }}@${{ secrets.DEV_SERVER}} "docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Pull latest image
        run: ssh ${{ secrets.dev_server_user }}@${{ secrets.dev_server}} "docker pull tomfordweb/devonwick-clp"
      - name: Run the image
        run: ssh ${{ secrets.dev_server_user }}@${{ secrets.dev_server}} "docker run -p 8080:80 tomfordweb/devonwick-clp"
