name: Scheduled database backup
on:
  schedule:
    - cron: "17 8 */7 * *"

jobs:
  backup-primary-db:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key for DEV_SERVER
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEV_SERVER_SSH_KEY }}
          known_hosts: "a-placeholder"

      - name: Add Dev server to known hosts
        run: ssh-keyscan -H ${{ secrets.DEV_SERVER }} >> ~/.ssh/known_hosts

      - name: Run Backup Script
        run: ssh ${{ secrets.dev_server_user }}@${{ secrets.dev_server}} "cd /srv/docker/devonwick-clp && ./backupDatabase sql_app.db"
